from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class UserJobMatchComponentResponse(BaseModel):
    name: str = Field(description="Stable scoring component key generated by the deterministic matcher.")
    weight: float = Field(description="Static component weight used by the deterministic match engine.")
    raw_score: float = Field(description="Component score before weighting, normalized to the 0-1 range.")
    weighted_score: float = Field(description="Component contribution after the static weight has been applied.")
    summary: str = Field(description="Technical deterministic summary of how this component was evaluated.")
    matched_terms: list[str] = Field(
        default_factory=list,
        description="Normalized terms that positively contributed to this scoring component.",
    )
    missing_terms: list[str] = Field(
        default_factory=list,
        description="Normalized terms that were expected by the job but not strongly evidenced in the profile.",
    )


class UserJobMatchScoreBreakdownResponse(BaseModel):
    component_key: str = Field(description="Stable component identifier used by the explanation generator.")
    label: str = Field(description="Frontend-safe human-readable label for the scoring component.")
    weight: float = Field(description="Static component weight used inside the deterministic matcher.")
    raw_score: float = Field(description="Component score before weighting, normalized to the 0-1 range.")
    weighted_score: float = Field(description="Final weighted contribution used inside the overall fit score.")
    impact: Literal["strong", "moderate", "weak"] = Field(
        description="Qualitative interpretation of the component score for UI presentation.",
    )
    summary: str = Field(description="Deterministic technical summary explaining how the component score was derived.")
    evidence_terms: list[str] = Field(
        default_factory=list,
        description="Matched normalized terms that positively supported the component.",
    )
    missing_terms: list[str] = Field(
        default_factory=list,
        description="Missing normalized terms that weakened the component score.",
    )


class UserJobMatchEvidencePointResponse(BaseModel):
    code: str = Field(description="Stable explanation code for analytics, validation, and frontend mapping.")
    title: str = Field(description="Short professional title for a positive evidence point.")
    detail: str = Field(description="User-facing deterministic explanation of why this signal supports the recommendation.")
    supporting_terms: list[str] = Field(
        default_factory=list,
        description="Normalized profile or job terms that directly support this evidence point.",
    )


class UserJobMatchGapResponse(BaseModel):
    code: str = Field(description="Stable explanation code representing a deterministic gap or caution signal.")
    title: str = Field(description="Short professional title for a gap or caution item.")
    detail: str = Field(description="User-facing deterministic explanation of what should be reviewed or improved.")
    severity: Literal["high", "medium", "low"] = Field(
        description="Severity band derived from deterministic scoring thresholds.",
    )
    missing_terms: list[str] = Field(
        default_factory=list,
        description="Normalized job terms not yet strongly represented in the subscriber profile.",
    )


class UserJobExternalSourceMetadataResponse(BaseModel):
    source_url: str = Field(default="", description="Original job-source URL used for live enrichment.")
    final_url: str | None = Field(default=None, description="Final resolved URL after redirects, if available.")
    source_domain: str | None = Field(default=None, description="Normalized host/domain for the original source page.")
    fetch_status: str = Field(default="unavailable", description="Fetch lifecycle state for the external source snapshot.")
    http_status: int | None = Field(default=None, description="HTTP response status captured during the last successful fetch attempt.")
    page_title: str | None = Field(default=None, description="HTML title extracted from the original source page when available.")
    site_name: str | None = Field(default=None, description="Display-safe site or publisher name extracted from the original page metadata.")
    fetched_at: str | None = Field(default=None, description="Timestamp when the source page was last fetched for enrichment.")
    content_digest: str | None = Field(default=None, description="Stable digest of the cleaned source text used for cache validation and change detection.")
    text_char_count: int = Field(default=0, description="Character count of the cleaned source text retained after normalization and clipping.")


class UserJobExternalSourceInsightsResponse(BaseModel):
    enrichment_status: Literal["unavailable", "cached", "live", "error"] = Field(
        default="unavailable",
        description="Indicates whether external source enrichment is missing, cached, freshly fetched, or unavailable due to an error.",
    )
    site_specific_requirements: list[str] = Field(
        default_factory=list,
        description="Deterministically extracted requirements or qualifications found only on the original source page.",
    )
    company_culture_clues: list[str] = Field(
        default_factory=list,
        description="Signals about company culture, benefits, or working style extracted from the original job page.",
    )
    responsibility_clues: list[str] = Field(
        default_factory=list,
        description="Responsibility statements or day-to-day expectations extracted from the original source page.",
    )
    technology_stack_terms: list[str] = Field(
        default_factory=list,
        description="Technology or tooling terms detected in the original page text without modifying the deterministic base score.",
    )
    original_source_metadata: UserJobExternalSourceMetadataResponse = Field(
        default_factory=UserJobExternalSourceMetadataResponse,
        description="Normalized metadata about the original source page used to enrich the contextual evidence packet.",
    )
    warning: str | None = Field(
        default=None,
        description="Fallback warning when external enrichment could not be refreshed or should be treated cautiously.",
    )




class UserJobAnalysisCoverageResponse(BaseModel):
    score: float = Field(default=0.0, description="Normalized 0-1 confidence score for how fully the job content was acquired and analyzed.")
    level: Literal["strong", "moderate", "limited"] = Field(
        default="limited",
        description="Qualitative band indicating whether the job-content packet is rich, usable, or still partial.",
    )
    summary: str = Field(default="", description="Deterministic summary of how complete the job-content packet is.")
    content_sources: list[str] = Field(
        default_factory=list,
        description="Stable identifiers for which content sources were available during job analysis.",
    )
    detected_signal_types: list[str] = Field(
        default_factory=list,
        description="Stable identifiers for the strongest structured signals extracted from the job content.",
    )
    warning: str | None = Field(
        default=None,
        description="Optional caution message when the job was ranked from partial content.",
    )


class UserJobMatchExplanationResponse(BaseModel):
    summary: str = Field(description="Primary deterministic recommendation summary for quick UI display.")
    fit_score: float = Field(description="Deterministic profile-to-job fit score on a 0-1 scale.")
    catalog_score: float = Field(description="Catalog-quality score reflecting trust, freshness, and readiness of the job entry.")
    final_score: float = Field(description="Final score returned by the deterministic ranking engine on a 0-1 scale.")
    behavioral_affinity_score: float | None = Field(
        default=None,
        description="Optional soft-personalization score derived from observed user interactions with similar jobs.",
    )
    matched_skill_terms: list[str] = Field(
        default_factory=list,
        description="Normalized skill terms that overlap strongly between the profile and the job.",
    )
    missing_skill_terms: list[str] = Field(
        default_factory=list,
        description="Normalized skill terms the job emphasizes but the profile does not yet strongly evidence.",
    )
    matched_location_terms: list[str] = Field(
        default_factory=list,
        description="Normalized location terms that align between subscriber preference and the job listing.",
    )
    matching_score_breakdown: list[UserJobMatchScoreBreakdownResponse] = Field(
        default_factory=list,
        description="Structured technical breakdown of the strongest deterministic scoring components.",
    )
    key_evidence_points: list[UserJobMatchEvidencePointResponse] = Field(
        default_factory=list,
        description="Positive deterministic signals that explain why the job is being recommended.",
    )
    gap_analysis: list[UserJobMatchGapResponse] = Field(
        default_factory=list,
        description="Deterministic gap or caution items the user should review before applying.",
    )
    top_reasons: list[str] = Field(
        default_factory=list,
        description="Short professional sentences summarizing the strongest deterministic recommendation reasons.",
    )
    analysis_coverage: UserJobAnalysisCoverageResponse = Field(
        default_factory=UserJobAnalysisCoverageResponse,
        description="Structured signal describing whether the job content was rich enough for confident deterministic analysis.",
    )
    external_source_insights: UserJobExternalSourceInsightsResponse = Field(
        default_factory=UserJobExternalSourceInsightsResponse,
        description="Dynamic but score-safe enrichment derived from the original job source page.",
    )
    components: list[UserJobMatchComponentResponse] = Field(
        default_factory=list,
        description="Raw deterministic score components retained for backward compatibility and advanced UI surfaces.",
    )


class UserJobListItemResponse(BaseModel):
    id: int = Field(description="Public job identifier returned by the Jobs/Matches APIs.")
    job_kind: Literal["legacy", "canonical"] = Field(
        default="legacy",
        description="Indicates whether the response item comes from the canonical job corpus or the legacy job table.",
    )
    source_name: str = Field(description="Display-safe source label for the job entry.")
    title: str = Field(description="Primary job title shown to the user.")
    company_name: str = Field(description="Display company name.")
    location: str | None = Field(default=None, description="Display-safe location summary for the job.")
    canonical_url: str = Field(description="Apply or detail URL for the job entry.")
    is_active: bool = Field(description="Whether the job is currently considered active in the catalog.")
    first_seen_at: str | None = Field(default=None, description="Timestamp when the system first saw the job record.")
    last_seen_at: str | None = Field(default=None, description="Timestamp when the system last refreshed or confirmed the job record.")
    matched: bool = Field(description="Whether the deterministic or legacy matching logic considers the job a positive match.")
    match_score: int | None = Field(default=None, description="Rounded 0-100 score displayed to end users.")
    matched_keywords: list[str] = Field(
        default_factory=list,
        description="Legacy-compatible keyword overlap list or matched canonical skill terms.",
    )
    workplace_type: str | None = Field(default=None, description="Normalized workplace mode if available.")
    employment_type: str | None = Field(default=None, description="Normalized employment type if available.")
    seniority: str | None = Field(default=None, description="Normalized seniority band if available.")
    posted_at: str | None = Field(default=None, description="Source posting date if available.")
    explanation: UserJobMatchExplanationResponse = Field(
        description="Deterministic structured explanation contract used by Jobs and Matches UI surfaces.",
    )


class UserJobListResponse(BaseModel):
    items: list[UserJobListItemResponse]
    page: int
    page_size: int
    total_items: int
    total_pages: int
    query: str | None
    only_matched: bool
    active_only: bool
    ranking_mode: Literal["legacy_keyword", "deterministic_matching"] = "legacy_keyword"


class UserJobInteractionRequest(BaseModel):
    source_surface: str = Field(default="jobs", min_length=1, max_length=64)
    dwell_seconds: int | None = Field(default=None, ge=0, le=3600)


class UserJobInteractionResponse(BaseModel):
    job_id: int
    job_kind: Literal["legacy", "canonical"]
    canonical_job_id: int | None = None
    interaction_type: Literal["impression", "open", "dwell", "save", "apply_click"]
    affinity_score: float
    impression_count: int
    open_count: int
    save_count: int
    apply_click_count: int
    total_dwell_seconds: int
    max_dwell_seconds: int
    last_interacted_at: str | None = None
