import {normalizeEmployerLanguage, type EmployerLanguage} from './employer-copy';

export type LocalizedText = Record<EmployerLanguage, string>;

export function getEmployerLanguage(locale: string): EmployerLanguage {
  return normalizeEmployerLanguage(locale);
}

export function text(locale: string, values: LocalizedText): string {
  return values[getEmployerLanguage(locale)];
}

export type AnalyticsCopy = ReturnType<typeof getEmployerAnalyticsCopy>;
export type SettingsCopy = ReturnType<typeof getEmployerSettingsCopy>;

export function getEmployerAnalyticsCopy(locale: string) {
  const lang = getEmployerLanguage(locale);

  const tr = {
    page: {
      eyebrow: 'İşe alım zekâ merkezi',
      title: 'İşe alım performansını yönetici netliğinde izleyin.',
      description:
        'Aday hunisi, kaynak verimi, süreç darboğazları, ilan kalitesi ve kampanya sağlığını tek ekranda görün. Bu sayfa karar toplantısı için hazırlanmış üretim kalitesinde bir analiz merkezidir.',
      export: 'Raporu dışa aktar',
      refresh: 'Verileri yenile',
      operatingScore: 'İşe alım işletim puanı',
      operatingScoreHelper: 'Aday kalitesi, ilan kalitesi ve hedef süre sağlığından hesaplanır.',
      searchLabel: 'Rol veya teknoloji ara',
      searchPlaceholder: 'React, Go, tasarım, ürün...',
      periodLabel: 'Dönem',
      lensLabel: 'Bakış açısı',
    },
    periods: {'7d': 'Son 7 gün', '30d': 'Son 30 gün', '90d': 'Son 90 gün'},
    lenses: {
      executive: {label: 'Yönetici özeti', description: 'Genel sağlık ve karar sinyalleri'},
      pipeline: {label: 'Süreç', description: 'Darboğaz ve hedef süre'},
      sourcing: {label: 'Kaynaklar', description: 'Aday kaynağı kalitesi'},
      quality: {label: 'Kalite', description: 'İlan ve aday uyumu'},
    },
    metrics: {
      activeJobs: {label: 'Aktif ilan', description: 'Yayında olan pozisyonlar'},
      qualifiedCandidates: {label: 'Nitelikli aday', description: 'Rol beklentisine güçlü uyan adaylar'},
      avgMatch: {label: 'Ortalama uyum puanı', description: 'Aday havuzundaki genel rol uyumu'},
      overdue: {label: 'Hedef süre dışı aday', description: 'Süreçte aksiyon bekleyen adaylar'},
    },
    funnel: {
      badge: 'Aday hunisi',
      title: 'Aşama dönüşümü ve hedef süre baskısı',
      description: 'Görüntülemeden işe alıma kadar her aşamadaki hacim, dönüşüm ve gecikme sinyalini gösterir.',
      report: 'Huni raporu',
      stagePrefix: 'Aşama',
      target: 'Hedef dönüşüm',
      actual: 'Gerçekleşen',
      overdue: 'hedef süre dışı',
      clear: 'Temiz',
      momentum: 'Momentum',
      stages: {
        views: 'Görüntüleme',
        applications: 'Başvuru',
        qualified: 'Nitelikli',
        shortlist: 'Kısa liste',
        interview: 'Görüşme',
        offer: 'Teklif',
        hired: 'İşe alım',
      },
    },
    sources: {
      badge: 'Kaynak kalitesi',
      title: 'Aday kaynağı verimi ve yatırım önceliği',
      description: 'Sadece kaç aday geldiğini değil; kalite, yanıt olasılığı ve maliyet baskısını birlikte okur.',
      action: 'Kampanyalara git',
      candidate: 'aday',
      quality: 'Kalite',
      response: 'Yanıt',
      cost: 'Maliyet',
      roi: 'Getiri',
      labels: {
        direct: 'Doğrudan başvuru',
        linkedin: 'LinkedIn',
        referral: 'Referans',
        job_board: 'İlan platformu',
        talent_radar: 'Yetenek Radarı',
        agency: 'Ajans',
        other: 'Diğer',
      },
      recommendations: {
        direct: 'Başvuru formundaki eleme sorularını güçlendirerek nitelikli aday oranını artırın.',
        linkedin: 'Kısa, kanıt odaklı davet mesajlarıyla yanıt oranını yükseltin.',
        referral: 'Referans adaylarını öncelikli değerlendirmeye alın; kalite ve kapanış olasılığı yüksek.',
        job_board: 'İlan kalitesini, maaş şeffaflığını ve rol kapsamını iyileştirin.',
        talent_radar: 'Yüksek niyetli adaylara kişiselleştirilmiş davet kampanyası açın.',
        agency: 'Ajans adaylarında kalite kontrol adımını sıkılaştırın.',
        other: 'Kaynak hacmini korurken nitelikli aday oranını yakından izleyin.',
      },
    },
    jobQuality: {
      badge: 'İlan kalitesi',
      title: 'İlan kalite merkezi',
      description: 'Düşük kalite puanı aday maliyetini artırır ve iyi adayların başvurudan vazgeçmesine yol açabilir.',
      action: 'İlanları aç',
      applicants: 'başvuru',
      qualified: 'nitelikli',
      firstRisk: 'İlk risk',
      noRisk: 'Açık risk yok',
      quality: 'Kalite',
      conversion: 'Dönüşüm',
      match: 'Uyum',
    },
    pipeline: {
      badge: 'Süreç sağlığı',
      title: 'Darboğaz ve hedef süre radarı',
      description: 'Hangi aşamada aday beklediğini ve hangi noktada ekibin aksiyon alması gerektiğini gösterir.',
      candidates: 'aday',
      targetDays: 'hedef gün',
      overdue: 'geciken',
      conversion: 'Dönüşüm',
    },
    campaign: {
      badge: 'Kampanya sağlığı',
      title: 'Davet kampanyası hazırlığı',
      description: 'Hazır mesajlar, insan kontrolü bekleyen adaylar ve blokerleri yönetici seviyesinde özetler.',
      ready: 'Hazır kampanya',
      review: 'Kontrol bekleyen mesaj',
      blocked: 'Blokerli aday',
      response: 'Ortalama yanıt tahmini',
      action: 'Kampanyaları aç',
    },
    chart: {
      badge: 'Haftalık kalite',
      title: 'Başvuru ve nitelikli aday akışı',
      applications: 'Başvuru',
      qualified: 'Nitelikli',
      days: {Mon: 'Pzt', Tue: 'Sal', Wed: 'Çar', Thu: 'Per', Fri: 'Cum', Sat: 'Cmt', Sun: 'Paz'},
    },
    insights: {
      badge: 'Yapay zeka işletim notları',
      title: 'Bu hafta öncelik verilmesi gerekenler',
      action: 'Aksiyon',
      items: [
        {
          id: 'pipeline-sla',
          title: 'Kısa liste aşaması hedef süre baskısı yaratıyor',
          description: 'Bazı adaylar hedef değerlendirme süresini aşmış durumda. Öncelik kısa liste ve ön eleme aşamalarında olmalı.',
          impact: 'Tahmini kapanış süresini 4-6 gün uzatabilir',
          action: 'Süreci aç',
          href: 'candidates',
          severity: 'warning' as const,
        },
        {
          id: 'hot-candidates',
          title: 'Yüksek niyetli aday fırsatı',
          description: 'Yüksek uyum ve yüksek niyet puanına sahip adaylarda ilk temas gecikirse yanıt olasılığı düşebilir.',
          impact: 'Bu hafta ek görüşme yaratabilir',
          action: 'Davet hazırla',
          href: 'candidates',
          severity: 'ai' as const,
        },
        {
          id: 'job-quality',
          title: 'İlan kalitesi kaynak maliyetini etkiliyor',
          description: 'Maaş şeffaflığı, çalışma modeli ve rol kapsamı iyileştirilirse nitelikli başvuru oranı artabilir.',
          impact: 'Başvuru kalitesinde ölçülebilir artış potansiyeli',
          action: 'İlanları iyileştir',
          href: 'jobs',
          severity: 'danger' as const,
        },
        {
          id: 'source-quality',
          title: 'Referans ve Yetenek Radarı daha kaliteli aday getiriyor',
          description: 'Bu iki kaynak hacim olarak küçük olsa da kalite ve yanıt tahmininde en güçlü segmentte.',
          impact: 'Kampanya bütçesini daha verimli kullanır',
          action: 'Kaynakları incele',
          href: 'analytics',
          severity: 'success' as const,
        },
      ],
    },
    boardPack: {
      badge: 'Yönetim özeti',
      title: 'Toplantıya hazır karar notları',
      items: [
        'Referans ve Yetenek Radarı en verimli aday kaynakları olarak öne çıkıyor.',
        'Kısa liste aşamasındaki gecikmeler kapanış hızını düşürüyor.',
        'Kampanya kontrol panosu insan onayını ve denetim izini görünür kılıyor.',
      ],
    },
    benchmarks: {
      badge: 'Pazar karşılaştırması',
      title: 'İşe alım kıyas göstergeleri',
      current: 'Mevcut',
      benchmark: 'Kıyas',
      items: [
        {label: 'Kısa listeye alma süresi', value: '3,2 gün', benchmark: '4,8 gün', positive: true},
        {label: 'Aday yanıt hızı', value: '%41', benchmark: '%34', positive: true},
        {label: 'Teklif kabul oranı', value: '%67', benchmark: '%61', positive: true},
        {label: 'Hedef süre dışı kontrol', value: '%22', benchmark: '%14', positive: false},
      ],
    },
  };

  const en = {
    page: {
      eyebrow: 'Hiring intelligence center',
      title: 'Track hiring performance with executive-level clarity.',
      description:
        'See candidate funnel, source efficiency, process bottlenecks, job quality and campaign health in one decision-ready analytics workspace.',
      export: 'Export report',
      refresh: 'Refresh data',
      operatingScore: 'Hiring operating score',
      operatingScoreHelper: 'Calculated from candidate quality, job quality and process health.',
      searchLabel: 'Search role or technology',
      searchPlaceholder: 'React, Go, design, product...',
      periodLabel: 'Period',
      lensLabel: 'Lens',
    },
    periods: {'7d': 'Last 7 days', '30d': 'Last 30 days', '90d': 'Last 90 days'},
    lenses: {
      executive: {label: 'Executive', description: 'Overall health and decision signals'},
      pipeline: {label: 'Pipeline', description: 'Bottlenecks and SLA'},
      sourcing: {label: 'Sourcing', description: 'Source quality'},
      quality: {label: 'Quality', description: 'Job and candidate fit'},
    },
    metrics: {
      activeJobs: {label: 'Active jobs', description: 'Open roles currently live'},
      qualifiedCandidates: {label: 'Qualified candidates', description: 'Candidates with strong role fit'},
      avgMatch: {label: 'Average match score', description: 'Overall fit across the talent pool'},
      overdue: {label: 'Overdue candidates', description: 'Candidates waiting for action'},
    },
    funnel: {
      badge: 'Candidate funnel',
      title: 'Stage conversion and process pressure',
      description: 'Track volume, conversion and delay signals from job views to hires.',
      report: 'Funnel report',
      stagePrefix: 'Stage',
      target: 'Target conversion',
      actual: 'Actual',
      overdue: 'overdue',
      clear: 'Clear',
      momentum: 'Momentum',
      stages: {
        views: 'Views',
        applications: 'Applications',
        qualified: 'Qualified',
        shortlist: 'Shortlist',
        interview: 'Interview',
        offer: 'Offer',
        hired: 'Hired',
      },
    },
    sources: {
      badge: 'Source quality',
      title: 'Source efficiency and investment priority',
      description: 'Evaluate not only candidate volume, but also quality, response likelihood and cost pressure.',
      action: 'Open campaigns',
      candidate: 'candidates',
      quality: 'Quality',
      response: 'Response',
      cost: 'Cost',
      roi: 'ROI',
      labels: {
        direct: 'Direct applicants',
        linkedin: 'LinkedIn',
        referral: 'Referral',
        job_board: 'Job board',
        talent_radar: 'Talent Radar',
        agency: 'Agency',
        other: 'Other',
      },
      recommendations: {
        direct: 'Improve screening questions to raise qualified applicant ratio.',
        linkedin: 'Use short, evidence-led outreach to increase response rate.',
        referral: 'Prioritize referral candidates; quality and close probability are strong.',
        job_board: 'Improve job quality, salary transparency and role scope.',
        talent_radar: 'Launch personalized outreach for high-intent candidates.',
        agency: 'Tighten quality checks for agency candidates.',
        other: 'Maintain volume while monitoring qualified candidate ratio.',
      },
    },
    jobQuality: {
      badge: 'Job quality',
      title: 'Job quality center',
      description: 'Low job quality increases candidate cost and can push strong candidates away before applying.',
      action: 'Open jobs',
      applicants: 'applicants',
      qualified: 'qualified',
      firstRisk: 'First risk',
      noRisk: 'No clear risk',
      quality: 'Quality',
      conversion: 'Conversion',
      match: 'Match',
    },
    pipeline: {
      badge: 'Process health',
      title: 'Bottleneck and SLA radar',
      description: 'See where candidates are waiting and where the team should act next.',
      candidates: 'candidates',
      targetDays: 'target days',
      overdue: 'overdue',
      conversion: 'Conversion',
    },
    campaign: {
      badge: 'Campaign health',
      title: 'Outreach campaign readiness',
      description: 'Executive summary of ready messages, human review workload and blockers.',
      ready: 'Ready campaigns',
      review: 'Messages in review',
      blocked: 'Blocked candidates',
      response: 'Average response estimate',
      action: 'Open campaigns',
    },
    chart: {
      badge: 'Weekly quality',
      title: 'Applications and qualified candidate flow',
      applications: 'Applications',
      qualified: 'Qualified',
      days: {Mon: 'Mon', Tue: 'Tue', Wed: 'Wed', Thu: 'Thu', Fri: 'Fri', Sat: 'Sat', Sun: 'Sun'},
    },
    insights: {
      badge: 'AI operating notes',
      title: 'What needs attention this week',
      action: 'Action',
      items: [
        {
          id: 'pipeline-sla',
          title: 'Shortlist stage is creating process pressure',
          description: 'Some candidates are waiting beyond the target review window. Focus on shortlist and screening stages first.',
          impact: 'May extend close time by 4-6 days',
          action: 'Open pipeline',
          href: 'candidates',
          severity: 'warning' as const,
        },
        {
          id: 'hot-candidates',
          title: 'High-intent candidate opportunity',
          description: 'Candidates with strong match and intent scores may lose response likelihood if outreach is delayed.',
          impact: 'Can create additional interviews this week',
          action: 'Prepare outreach',
          href: 'candidates',
          severity: 'ai' as const,
        },
        {
          id: 'job-quality',
          title: 'Job quality is affecting source cost',
          description: 'Salary transparency, work model clarity and role scope can improve qualified applicant rate.',
          impact: 'Potential measurable increase in applicant quality',
          action: 'Improve jobs',
          href: 'jobs',
          severity: 'danger' as const,
        },
        {
          id: 'source-quality',
          title: 'Referral and Talent Radar drive stronger quality',
          description: 'These sources have lower volume but stronger quality and response estimates.',
          impact: 'Improves campaign budget efficiency',
          action: 'Review sources',
          href: 'analytics',
          severity: 'success' as const,
        },
      ],
    },
    boardPack: {
      badge: 'Board pack',
      title: 'Decision notes ready for leadership',
      items: [
        'Referral and Talent Radar are the most efficient candidate sources.',
        'Shortlist delays are reducing close speed.',
        'Campaign review board makes human approval and audit trail visible.',
      ],
    },
    benchmarks: {
      badge: 'Market benchmark',
      title: 'Hiring benchmark indicators',
      current: 'Current',
      benchmark: 'Benchmark',
      items: [
        {label: 'Time to shortlist', value: '3.2 days', benchmark: '4.8 days', positive: true},
        {label: 'Candidate response speed', value: '41%', benchmark: '34%', positive: true},
        {label: 'Offer acceptance rate', value: '67%', benchmark: '61%', positive: true},
        {label: 'Overdue reviews', value: '22%', benchmark: '14%', positive: false},
      ],
    },
  };

  return lang === 'tr' ? tr : en;
}

export function getEmployerSettingsCopy(locale: string) {
  const lang = getEmployerLanguage(locale);

  const tr = {
    page: {
      eyebrow: 'Çalışma alanı kontrol merkezi',
      title: 'İşveren çalışma alanını üretim kalitesinde yönetin.',
      description:
        'Şirket profili, ekip yetkileri, güvenlik, bildirimler, marka görünürlüğü, entegrasyonlar ve denetim kayıtlarını tek merkezden yönetin.',
      readiness: 'Hazırlık',
      roleAccess: 'Rol tabanlı yetki hazır',
      securityPosture: 'Güvenlik durumu',
      save: 'Değişiklikleri kaydet',
      invite: 'Üye davet et',
      exportAudit: 'Denetim kaydını dışa aktar',
    },
    tabs: {
      company: {label: 'Şirket', description: 'Profil, lokasyon ve işe alım hedefleri'},
      team: {label: 'Ekip ve yetkiler', description: 'Üyeler, roller ve erişim kapsamları'},
      security: {label: 'Güvenlik', description: 'Tek oturum açma, doğrulama ve oturum politikaları'},
      notifications: {label: 'Bildirimler', description: 'Hedef süre, aday ve kampanya uyarıları'},
      brand: {label: 'Marka', description: 'Aday deneyimi ve işveren algısı'},
      integrations: {label: 'Entegrasyonlar', description: 'Takvim, e-posta, veri ve API akışları'},
      audit: {label: 'Denetim', description: 'Yapay zeka, erişim ve karar kayıtları'},
    },
    status: {active: 'Aktif', invited: 'Davetli', limited: 'Sınırlı', connected: 'Bağlı', available: 'Hazır', needs_review: 'Kontrol gerekli'},
    risk: {low: 'Düşük risk', medium: 'Orta risk', high: 'Yüksek risk'},
    common: {manage: 'Yönet', configure: 'Yapılandır', preview: 'Önizle', save: 'Kaydet', enabled: 'Açık', disabled: 'Kapalı'},
    company: {
      eyebrow: 'Şirket profili',
      title: 'Şirket kimliği ve işe alım işletim modeli',
      description: 'Adaya gösterilecek temel bilgileri ve işe alım hedeflerinizi yönetin. Bu alan şirket sayfası, ilan kalitesi ve davet mesajlarına kaynak olur.',
      fields: {name: 'Şirket adı', website: 'Web sitesi', location: 'Ana lokasyon', goal: 'İşe alım hedefi', summary: 'Şirket kısa açıklaması'},
      values: {
        name: 'NoyTera Teknoloji A.Ş.',
        website: 'https://noytera.com',
        location: 'İstanbul, Türkiye',
        goal: 'Üçüncü çeyrekte 18 teknik rolü kapatmak',
        summary: 'NoyTera, işveren ve aday eşleşmesini daha hızlı, açıklanabilir ve adil hale getiren yapay zeka destekli işe alım platformudur.',
      },
      actions: {save: 'Profili kaydet', preview: 'Aday görünümünü önizle', editBrand: 'Marka kitini düzenle'},
      cardTitle: 'İşveren marka kartı',
      cardDescription: 'İlanlarda, davet mesajlarında ve şirket sayfasında kullanılacak kısa marka kimliği.',
      signals: ['Hibrit çalışma', 'Şeffaf süreç', 'Yapay zeka destekli işe alım ekibi'],
    },
    team: {
      eyebrow: 'Ekip ve rol tabanlı yetkilendirme',
      title: 'Kim neyi görebilir ve hangi kararı alabilir?',
      description: 'Üretim kalitesinde B2B ürün için ekip yetkileri açık, izlenebilir ve dar kapsamlı olmalıdır.',
      invite: 'Üye davet et',
      membersTitle: 'Takım üyeleri',
      rolesTitle: 'Rol matrisi',
      columns: {member: 'Üye', role: 'Rol', status: 'Durum', scope: 'Erişim kapsamı', active: 'Son etkinlik'},
      members: [
        {name: 'Elif Korkmaz', email: 'elif@noytera.com', role: 'Sahip', status: 'active', lastActive: 'Şimdi aktif', scope: 'Tüm şirket'},
        {name: 'Mert Aksoy', email: 'mert@noytera.com', role: 'İşe alım uzmanı', status: 'active', lastActive: '18 dk önce', scope: 'Mühendislik işe alımı'},
        {name: 'Zeynep Arslan', email: 'zeynep@noytera.com', role: 'İşe alım yöneticisi', status: 'limited', lastActive: 'Dün', scope: 'Ön yüz ve ürün'},
        {name: 'Can Demir', email: 'can@noytera.com', role: 'Görüntüleyici', status: 'invited', lastActive: 'Davet bekliyor', scope: 'Analitik'},
      ],
      roles: [
        {role: 'Sahip', description: 'Faturalandırma, güvenlik, ekip ve tüm işe alım verisine tam erişim.', permissions: ['Tüm ayarlar', 'Faturalandırma', 'Denetim dışa aktarımı', 'Tek oturum açma yönetimi'], risk: 'high'},
        {role: 'Yönetici', description: 'Operasyon ayarlarını ve takım üyelerini yönetir.', permissions: ['Takım yönetimi', 'İlan onayı', 'Kampanya kontrolü', 'Raporlar'], risk: 'medium'},
        {role: 'İşe alım uzmanı', description: 'Aday, süreç, kampanya ve not akışlarını yönetir.', permissions: ['Aday yönetimi', 'Kampanya taslağı', 'Not ve etiket', 'Süreç yönetimi'], risk: 'medium'},
        {role: 'İşe alım yöneticisi', description: 'Kendi pozisyonları için adayları değerlendirir.', permissions: ['Değerlendirme formu', 'Yorum', 'Kısa liste kontrolü', 'Aday 360'], risk: 'low'},
        {role: 'Görüntüleyici', description: 'Raporları ve belirlenen aday profillerini görüntüler.', permissions: ['Analitik görüntüle', 'Kısıtlı aday görüntüle'], risk: 'low'},
      ],
    },
    security: {
      eyebrow: 'Güvenlik ve veri politikaları',
      title: 'Hassas aday verisini güvenli ve izlenebilir yönetin.',
      description: 'Tek oturum açma, çok adımlı doğrulama, veri maskeleme ve insan kontrolü politikalarını üretim ortamına hazır hale getirin.',
      items: [
        {title: 'Çok adımlı doğrulama zorunlu', description: 'Tüm takım üyeleri için ek doğrulama istenir.', enabled: true},
        {title: 'Tek oturum açma hazır modu', description: 'Kurumsal kimlik sağlayıcı bağlantısı için yapılandırma alanı hazır.', enabled: false},
        {title: 'Maaş beklentisi maskeleme', description: 'Hassas ücret alanları rol iznine göre gizlenir.', enabled: true},
        {title: 'Yapay zeka mesaj kontrolü zorunlu', description: 'Kampanya mesajları gönderimden önce insan kontrolünden geçer.', enabled: true},
      ],
      gapsTitle: 'Kurumsal tamamlanacaklar',
      gaps: ['Tek oturum açma yapılandırması', 'Veri saklama politikası', 'Denetim kaydı dışa aktarımı'],
    },
    notifications: {
      eyebrow: 'İletişim kontrol merkezi',
      title: 'Ekip bildirimlerini rol, kanal ve sessiz saatlere göre yönetin.',
      description: 'Gereksiz bildirim gürültüsünü azaltıp aday, kampanya ve güvenlik risklerini doğru kişiye yönlendirin.',
      controlsTitle: 'Bildirim kanalları',
      routingTitle: 'Rol bazlı yönlendirme',
      quietTitle: 'Sessiz saatler ve teslimat',
      teamTitle: 'Ekip kapsaması',
      loading: 'İletişim tercihleri yükleniyor...',
      errorTitle: 'İletişim tercihleri alınamadı',
      retry: 'Tekrar dene',
      updatedAt: 'Son güncelleme',
      activeMembers: 'Aktif üye',
      invitedMembers: 'Davet bekleyen',
      defaultChannel: 'Varsayılan kanal',
      notificationEmails: 'Ek bildirim e-postaları',
      notificationEmailsHelp: 'Virgülle ayırarak en fazla 10 adres ekleyin.',
      quietStart: 'Başlangıç',
      quietEnd: 'Bitiş',
      timezone: 'Saat dilimi',
      mandatory: 'Zorunlu',
      saving: 'Kaydediliyor',
      controls: [
        {key: 'candidate_alerts_enabled', title: 'Hedef süre dışı aday uyarısı', description: 'Aday süreçte bekleme sınırını aşınca sorumlu kişiye bildirim gider.'},
        {key: 'campaign_review_enabled', title: 'Kampanya kontrol kuyruğu', description: 'Davet mesajları kontrol panosunda birikirse ekip uyarılır.'},
        {key: 'weekly_leadership_digest_enabled', title: 'Haftalık yönetim özeti', description: 'Yönetici ekibe haftalık işe alım performans özeti hazırlanır.'},
        {key: 'product_updates_enabled', title: 'Ürün duyuruları', description: 'Yeni işveren paneli özellikleri ve operasyon notları paylaşılır.'},
        {key: 'security_alerts_enabled', title: 'Güvenlik uyarıları', description: 'Oturum, yetki ve hassas veri olayları her zaman görünür kalır.', locked: true},
      ],
      channels: {email: 'E-posta', in_app: 'Uygulama içi', email_and_in_app: 'E-posta + uygulama'},
      routeLabels: {owner: 'Sahip', admin: 'Yönetici', recruiter: 'İşe alım uzmanı', hiring_manager: 'İşe alım yöneticisi'},
      routes: {
        route_overdue_candidates_to: 'Hedef süre dışı adaylar',
        route_hot_candidates_to: 'Sıcak adaylar',
        route_campaign_review_to: 'Kampanya kontrol kuyruğu',
        route_weekly_digest_to: 'Haftalık yönetim özeti',
      },
    },
    brand: {
      eyebrow: 'İşveren markası',
      title: 'Adayın gördüğü güven sinyallerini yönetin.',
      description: 'Yanıt sözü, süreç şeffaflığı ve iletişim tonu aday dönüşümünü doğrudan etkiler.',
      cards: [
        {label: 'Yanıt sözü', value: '5 iş günü', description: 'Nitelikli adaylara dönüş hedefi'},
        {label: 'Süreç adımı', value: '4 aşama', description: 'Başvurudan teklife açık süreç'},
        {label: 'İletişim tonu', value: 'Net ve sıcak', description: 'Davet ve ret mesajı standardı'},
      ],
    },
    integrations: {
      eyebrow: 'Entegrasyonlar',
      title: 'İşe alım akışını mevcut araçlarınıza bağlayın.',
      description: 'Takvim, e-posta, olay bildirimi ve dışa aktarım bağlantıları üretim kullanımına hazırlanır.',
      items: [
        {name: 'Google Takvim', description: 'Görüşme planlama ve uygun saat önerileri.', status: 'available'},
        {name: 'Gmail / SMTP', description: 'Davet ve takip mesajları için e-posta gönderimi.', status: 'available'},
        {name: 'API olay bildirimi', description: 'Aday ve kampanya olaylarını dış sistemlere iletin.', status: 'needs_review'},
        {name: 'ATS dışa aktarımı', description: 'Aday ve süreç verilerini başka sistemlere aktarın.', status: 'connected'},
      ],
    },
    audit: {
      eyebrow: 'Denetim kayıtları',
      title: 'Kararlar, yapay zeka önerileri ve erişimler izlenebilir olsun.',
      description: 'Kurumsal satışta güven katmanı için karar kayıtları, insan kontrolü ve hassas veri erişimi görünür olmalıdır.',
      coverage: 'Kapsama',
      events: [
        {title: 'Yapay zeka kampanya mesajı insan kontrolünden geçti', description: '3 aday gönderime hazır olarak işaretlendi.', actor: 'Mert Aksoy', time: '12 dk önce', tone: 'success'},
        {title: 'Rol kapsamı güncellendi', description: 'İşe alım yöneticisi rolü sadece kendi pozisyonlarını görecek şekilde sınırlandı.', actor: 'Elif Korkmaz', time: 'Bugün 10:18', tone: 'info'},
        {title: 'Maaş alanı görünürlük politikası değişti', description: 'Görüntüleyici rolü için ücret alanları maskelendi.', actor: 'Sistem', time: 'Dün 16:40', tone: 'warning'},
      ],
      readiness: [
        {label: 'Yapay zeka kontrol kapsaması', value: 94},
        {label: 'Rol kapsamlı erişim', value: 88},
        {label: 'Hassas veri maskeleme', value: 82},
        {label: 'Dışa aktarılabilir kayıt', value: 76},
      ],
    },
  };

  const en = {
    page: {
      eyebrow: 'Workspace control center',
      title: 'Manage the employer workspace with production-grade controls.',
      description:
        'Control company profile, team access, security, notifications, brand presence, integrations and audit records from one workspace.',
      readiness: 'Readiness',
      roleAccess: 'Role-based access ready',
      securityPosture: 'Security posture',
      save: 'Save changes',
      invite: 'Invite member',
      exportAudit: 'Export audit log',
    },
    tabs: {
      company: {label: 'Company', description: 'Profile, location and hiring goals'},
      team: {label: 'Team and access', description: 'Members, roles and access scopes'},
      security: {label: 'Security', description: 'Single sign-on, authentication and session policies'},
      notifications: {label: 'Notifications', description: 'SLA, candidate and campaign alerts'},
      brand: {label: 'Brand', description: 'Candidate experience and employer brand'},
      integrations: {label: 'Integrations', description: 'Calendar, email, data and API flows'},
      audit: {label: 'Audit', description: 'AI, access and decision records'},
    },
    status: {active: 'Active', invited: 'Invited', limited: 'Limited', connected: 'Connected', available: 'Available', needs_review: 'Needs review'},
    risk: {low: 'Low risk', medium: 'Medium risk', high: 'High risk'},
    common: {manage: 'Manage', configure: 'Configure', preview: 'Preview', save: 'Save', enabled: 'Enabled', disabled: 'Disabled'},
    company: {
      eyebrow: 'Company profile',
      title: 'Company identity and hiring operating model',
      description: 'Manage the candidate-facing company information and hiring goals used by your brand page, job quality and outreach messages.',
      fields: {name: 'Company name', website: 'Website', location: 'Main location', goal: 'Hiring goal', summary: 'Company short description'},
      values: {
        name: 'NoyTera Technology Inc.',
        website: 'https://noytera.com',
        location: 'Istanbul, Türkiye',
        goal: 'Close 18 technical roles in Q3',
        summary: 'NoyTera is an AI-assisted hiring platform that makes employer and candidate matching faster, explainable and fair.',
      },
      actions: {save: 'Save profile', preview: 'Preview candidate view', editBrand: 'Edit brand kit'},
      cardTitle: 'Employer brand card',
      cardDescription: 'Short brand identity used in jobs, outreach messages and the company page.',
      signals: ['Hybrid work', 'Transparent process', 'AI-assisted hiring team'],
    },
    team: {
      eyebrow: 'Team and role-based access',
      title: 'Control who can see what and who can make decisions.',
      description: 'A production-grade B2B product needs team permissions that are clear, traceable and scoped.',
      invite: 'Invite member',
      membersTitle: 'Team members',
      rolesTitle: 'Role matrix',
      columns: {member: 'Member', role: 'Role', status: 'Status', scope: 'Access scope', active: 'Last active'},
      members: [
        {name: 'Elif Korkmaz', email: 'elif@noytera.com', role: 'Owner', status: 'active', lastActive: 'Active now', scope: 'Full company'},
        {name: 'Mert Aksoy', email: 'mert@noytera.com', role: 'Recruiter', status: 'active', lastActive: '18 min ago', scope: 'Engineering hiring'},
        {name: 'Zeynep Arslan', email: 'zeynep@noytera.com', role: 'Hiring Manager', status: 'limited', lastActive: 'Yesterday', scope: 'Frontend and product'},
        {name: 'Can Demir', email: 'can@noytera.com', role: 'Viewer', status: 'invited', lastActive: 'Invitation pending', scope: 'Analytics'},
      ],
      roles: [
        {role: 'Owner', description: 'Full access to billing, security, team and all hiring data.', permissions: ['All settings', 'Billing', 'Audit export', 'Single sign-on management'], risk: 'high'},
        {role: 'Admin', description: 'Manages operational settings and team members.', permissions: ['Team management', 'Job approval', 'Campaign review', 'Reports'], risk: 'medium'},
        {role: 'Recruiter', description: 'Manages candidates, process, campaigns and notes.', permissions: ['Candidate management', 'Campaign draft', 'Notes and tags', 'Pipeline'], risk: 'medium'},
        {role: 'Hiring Manager', description: 'Reviews candidates for assigned roles.', permissions: ['Scorecard', 'Comments', 'Shortlist review', 'Candidate 360'], risk: 'low'},
        {role: 'Viewer', description: 'Views reports and selected candidate profiles.', permissions: ['View analytics', 'View limited candidate profiles'], risk: 'low'},
      ],
    },
    security: {
      eyebrow: 'Security and data policies',
      title: 'Keep sensitive candidate data secure and traceable.',
      description: 'Prepare single sign-on, multi-factor authentication, data masking and human review policies for production use.',
      items: [
        {title: 'Require multi-factor authentication', description: 'All team members must use additional authentication.', enabled: true},
        {title: 'Single sign-on ready mode', description: 'Configuration area is ready for enterprise identity providers.', enabled: false},
        {title: 'Salary expectation masking', description: 'Sensitive compensation fields are hidden based on role permission.', enabled: true},
        {title: 'Require AI message review', description: 'Campaign messages require human review before sending.', enabled: true},
      ],
      gapsTitle: 'Enterprise gaps to close',
      gaps: ['Single sign-on configuration', 'Data retention policy', 'Audit log export'],
    },
    notifications: {
      eyebrow: 'Communication control center',
      title: 'Manage team alerts by role, channel and quiet hours.',
      description: 'Reduce notification noise while routing candidate, campaign and security risks to the right person.',
      controlsTitle: 'Notification channels',
      routingTitle: 'Role-based routing',
      quietTitle: 'Quiet hours and delivery',
      teamTitle: 'Team coverage',
      loading: 'Loading communication preferences...',
      errorTitle: 'Communication preferences could not be loaded',
      retry: 'Try again',
      updatedAt: 'Last updated',
      activeMembers: 'Active members',
      invitedMembers: 'Pending invites',
      defaultChannel: 'Default channel',
      notificationEmails: 'Extra notification emails',
      notificationEmailsHelp: 'Separate up to 10 addresses with commas.',
      quietStart: 'Start',
      quietEnd: 'End',
      timezone: 'Time zone',
      mandatory: 'Mandatory',
      saving: 'Saving',
      controls: [
        {key: 'candidate_alerts_enabled', title: 'Overdue candidate alert', description: 'Notify the responsible team when a candidate exceeds the review target window.'},
        {key: 'campaign_review_enabled', title: 'Campaign review queue', description: 'Alert the team when outreach drafts accumulate in the review board.'},
        {key: 'weekly_leadership_digest_enabled', title: 'Weekly leadership digest', description: 'Prepare a weekly hiring performance summary for leadership.'},
        {key: 'product_updates_enabled', title: 'Product updates', description: 'Share employer workspace releases and operational notes.'},
        {key: 'security_alerts_enabled', title: 'Security alerts', description: 'Session, permission and sensitive-data events always remain visible.', locked: true},
      ],
      channels: {email: 'Email', in_app: 'In-app', email_and_in_app: 'Email + in-app'},
      routeLabels: {owner: 'Owner', admin: 'Admin', recruiter: 'Recruiter', hiring_manager: 'Hiring manager'},
      routes: {
        route_overdue_candidates_to: 'Overdue candidates',
        route_hot_candidates_to: 'Hot candidates',
        route_campaign_review_to: 'Campaign review queue',
        route_weekly_digest_to: 'Weekly leadership digest',
      },
    },
    brand: {
      eyebrow: 'Employer brand',
      title: 'Manage the trust signals candidates see.',
      description: 'Response promise, process transparency and communication tone directly affect candidate conversion.',
      cards: [
        {label: 'Response promise', value: '5 business days', description: 'Target response time for qualified candidates'},
        {label: 'Process steps', value: '4 stages', description: 'Clear path from application to offer'},
        {label: 'Communication tone', value: 'Clear and warm', description: 'Standard for outreach and rejection messages'},
      ],
    },
    integrations: {
      eyebrow: 'Integrations',
      title: 'Connect hiring workflows to your existing tools.',
      description: 'Prepare calendar, email, event notification and export connections for production use.',
      items: [
        {name: 'Google Calendar', description: 'Interview scheduling and availability suggestions.', status: 'available'},
        {name: 'Gmail / SMTP', description: 'Email delivery for outreach and follow-up messages.', status: 'available'},
        {name: 'API event notification', description: 'Send candidate and campaign events to external systems.', status: 'needs_review'},
        {name: 'ATS export', description: 'Export candidate and process data to other systems.', status: 'connected'},
      ],
    },
    audit: {
      eyebrow: 'Audit records',
      title: 'Make decisions, AI recommendations and access traceable.',
      description: 'Enterprise trust requires visible decision records, human review and sensitive data access history.',
      coverage: 'Coverage',
      events: [
        {title: 'AI campaign message passed human review', description: '3 candidates were marked as ready to send.', actor: 'Mert Aksoy', time: '12 min ago', tone: 'success'},
        {title: 'Role scope updated', description: 'Hiring Manager role was limited to assigned positions only.', actor: 'Elif Korkmaz', time: 'Today 10:18', tone: 'info'},
        {title: 'Salary field visibility policy changed', description: 'Compensation fields were masked for the Viewer role.', actor: 'System', time: 'Yesterday 16:40', tone: 'warning'},
      ],
      readiness: [
        {label: 'AI review coverage', value: 94},
        {label: 'Role-scoped access', value: 88},
        {label: 'Sensitive data masking', value: 82},
        {label: 'Exportable records', value: 76},
      ],
    },
  };

  return lang === 'tr' ? tr : en;
}
