import {normalizeEmployerLanguage, type EmployerLanguage} from './employer-copy';
import type {EmployerCandidateStatus, EmployerRiskLevel, EmployerWorkModel} from '@/types/employer';
import type {EmployerCandidateOpportunity} from '@/types/employer';

export function getJobsTalentLanguage(locale: string): EmployerLanguage {
  return normalizeEmployerLanguage(locale);
}

export const candidateStatusLabels: Record<EmployerLanguage, Record<EmployerCandidateStatus, string>> = {
  tr: {
    new: 'Yeni',
    reviewed: 'İncelendi',
    shortlisted: 'Kısa liste',
    interview: 'Görüşme',
    offer: 'Teklif',
    hired: 'İşe alındı',
    rejected: 'Reddedildi',
  },
  en: {
    new: 'New',
    reviewed: 'Reviewed',
    shortlisted: 'Shortlisted',
    interview: 'Interview',
    offer: 'Offer',
    hired: 'Hired',
    rejected: 'Rejected',
  },
};

export const workModelLabels: Record<EmployerLanguage, Record<EmployerWorkModel | 'flexible', string>> = {
  tr: {office: 'Ofis', hybrid: 'Hibrit', remote: 'Uzaktan', flexible: 'Esnek'},
  en: {office: 'Office', hybrid: 'Hybrid', remote: 'Remote', flexible: 'Flexible'},
};

export const availabilityLabels: Record<EmployerLanguage, Record<EmployerCandidateOpportunity['availability'], string>> = {
  tr: {immediate: 'Hemen', two_weeks: '2 hafta', one_month: '1 ay', passive: 'Pasif'},
  en: {immediate: 'Immediate', two_weeks: '2 weeks', one_month: '1 month', passive: 'Passive'},
};

export const candidateSourceLabels: Record<EmployerLanguage, Record<EmployerCandidateOpportunity['source'], string>> = {
  tr: {
    direct: 'Doğrudan başvuru',
    linkedin: 'LinkedIn',
    referral: 'Referans',
    job_board: 'İlan platformu',
    talent_radar: 'Yetenek Radarı',
    agency: 'Ajans',
    other: 'Diğer',
  },
  en: {
    direct: 'Direct application',
    linkedin: 'LinkedIn',
    referral: 'Referral',
    job_board: 'Job board',
    talent_radar: 'Talent Radar',
    agency: 'Agency',
    other: 'Other',
  },
};

export function getEmployerRiskLabel(locale: string, level: EmployerRiskLevel): string {
  const lang = getJobsTalentLanguage(locale);
  const labels: Record<EmployerLanguage, Record<EmployerRiskLevel, string>> = {
    tr: {healthy: 'Sağlıklı', watch: 'Takipte', risk: 'Riskli', critical: 'Kritik'},
    en: {healthy: 'Healthy', watch: 'Watching', risk: 'At risk', critical: 'Critical'},
  };
  return labels[lang][level];
}

export function getEmployerJobsCopy(locale: string) {
  const lang = getJobsTalentLanguage(locale);
  const tr = {
    page: {
      aiReady: 'Yapay zekâ ilan stüdyosu hazır',
      themeActive: 'Okunabilir tema aktif',
      releaseBadge: 'Üretim kalitesi',
      title: 'İlan yönetimi artık sadece liste değil, kalite kontrol merkezi.',
      description: 'Her ilan için kalite puanı, risk sinyalleri, nitelikli aday oranı ve yayın iyileştirme önerilerini tek ekranda görün.',
      newJob: 'Yeni ilan oluştur',
      optimizeAll: 'Tüm ilanları iyileştir',
      opportunity: 'Bugünün fırsatı',
      opportunityText: (quality: number, match: number) => `Kalite puanı ${quality}, ortalama uyum %${match}. Şimdi iyileştirilirse kısa liste hızı artabilir.`,
      openOpportunity: 'Fırsatı aç',
      activeJobs: 'Aktif ilan',
      activeJobsDesc: 'Yayında ve aday kabul ediyor',
      qualifiedCandidates: 'Nitelikli aday',
      totalApplicants: (total: number) => `${total} toplam başvuru içinden`,
      averageQuality: 'Ortalama kalite',
      averageQualityDesc: 'İlan kalite puanı ortalaması',
      riskyJobs: 'Riskli ilan',
      riskyJobsDesc: 'Bugün aksiyon bekleyen ilan',
      portfolioEyebrow: 'İlan kontrol merkezi',
      portfolioTitle: 'İlan portföyü',
      portfolioDesc: 'Filtrele, kalite puanını izle, riskleri gör ve doğru ilanı hızlıca iyileştir.',
      customizeView: 'Görünümü özelleştir',
      searchPlaceholder: 'İlan, lokasyon, departman veya teknoloji ara...',
      riskFilter: 'Risk filtresi',
      noResultsTitle: 'Bu filtrelerle ilan bulunamadı',
      noResultsDesc: 'Arama veya risk filtrelerini gevşeterek portföyünüzdeki diğer ilanları görüntüleyebilirsiniz.',
      clearFilters: 'Filtreleri temizle',
      quickActionsEyebrow: 'Hızlı aksiyonlar',
      quickActionsTitle: 'İlan sağlığını yükselt',
      quickActions: [
        'Maaş bandı gizli ilanları tespit et',
        'Zorunlu kriterleri tercih edilen özelliklerden ayır',
        'Uzaktan/hibrit bilgisini başlıkta görünür yap',
        'Eleme sorularını otomatik üret',
      ],
    },
    filters: {
      status: [
        {label: 'Tümü', value: 'all'},
        {label: 'Aktif', value: 'active'},
        {label: 'Duraklatıldı', value: 'paused'},
        {label: 'Kapandı', value: 'closed'},
        {label: 'Taslak', value: 'draft'},
      ],
      risks: [
        {label: 'Tüm riskler', value: 'all'},
        {label: 'Sağlıklı', value: 'healthy'},
        {label: 'Takipte', value: 'watch'},
        {label: 'Riskli', value: 'risk'},
        {label: 'Kritik', value: 'critical'},
      ],
    },
    card: {
      statuses: {active: 'Aktif', paused: 'Duraklatıldı', closed: 'Kapandı', draft: 'Taslak'},
      aiWatching: 'Yapay zekâ izliyor',
      edit: 'Düzenle',
      publish: 'Yayına al',
      pause: 'Duraklat',
      more: 'Diğer işlemler',
      applications: 'Başvuru',
      qualified: 'nitelikli',
      match: 'Uyum',
      average: 'Ort.',
      strongSignal: 'Kısa liste için güçlü sinyal',
      views: 'Görüntüleme',
      conversion: 'Dönüşüm',
      salary: 'Maaş',
      salaryVisible: 'Şeffaf',
      salaryHidden: 'Gizli',
      salaryRangeMissing: 'Maaş bandı yok',
      salaryVisiblePrefix: 'Görünür',
      salaryHiddenPrefix: 'Gizli',
      riskSignals: 'Yapay zekâ risk sinyalleri',
    },
    quality: {
      badge: 'İlan kalitesi',
      description: 'Yayın kalitesi, aday havuzu etkisi ve dönüşüm riski.',
      scoreLabel: 'Kalite',
      risk: 'Risk',
      watch: 'Takip',
      conversion: 'Dönüşüm',
      optimize: 'İlanı iyileştir',
      preview: 'Önizle',
    },
    metricTrends: {week: 'bu hafta', quality: 'kalite', improved: 'iyileşti', risk: 'risk'},
    pagination: {
      previous: 'Önceki',
      next: 'Sonraki',
      pageSize: 'Sayfa başına',
      summary: (start: number, end: number, total: number) =>
        total === 0 ? 'Kayıt yok' : `${start}-${end} / ${total} ilan`,
    },
  };

  const en = {
    page: {
      aiReady: 'AI Job Studio ready',
      themeActive: 'Readable theme active',
      releaseBadge: 'Production quality',
      title: 'Job management is now a quality control center, not just a list.',
      description: 'See quality score, risk signals, qualified candidate ratio and publishing recommendations for every job in one workspace.',
      newJob: 'Create new job',
      optimizeAll: 'Optimize all jobs',
      opportunity: "Today's opportunity",
      opportunityText: (quality: number, match: number) => `Quality score ${quality}, average match ${match}%. Optimizing now can improve shortlist velocity.`,
      openOpportunity: 'Open opportunity',
      activeJobs: 'Active jobs',
      activeJobsDesc: 'Live and accepting candidates',
      qualifiedCandidates: 'Qualified candidates',
      totalApplicants: (total: number) => `from ${total} total applicants`,
      averageQuality: 'Average quality',
      averageQualityDesc: 'Average Job Quality Score',
      riskyJobs: 'At-risk jobs',
      riskyJobsDesc: 'Jobs waiting for action today',
      portfolioEyebrow: 'Job Control Center',
      portfolioTitle: 'Job portfolio',
      portfolioDesc: 'Filter, monitor quality, surface risks and optimize the right job quickly.',
      customizeView: 'Customize view',
      searchPlaceholder: 'Search job, location, department or technology...',
      riskFilter: 'Risk filter',
      noResultsTitle: 'No jobs found with these filters',
      noResultsDesc: 'Relax the search or risk filters to view other jobs in your portfolio.',
      clearFilters: 'Clear filters',
      quickActionsEyebrow: 'Quick actions',
      quickActionsTitle: 'Improve job health',
      quickActions: [
        'Detect jobs with hidden salary ranges',
        'Separate must-have criteria from nice-to-have requirements',
        'Make remote/hybrid model visible in the title',
        'Generate screening questions automatically',
      ],
    },
    filters: {
      status: [
        {label: 'All', value: 'all'},
        {label: 'Active', value: 'active'},
        {label: 'Paused', value: 'paused'},
        {label: 'Closed', value: 'closed'},
        {label: 'Draft', value: 'draft'},
      ],
      risks: [
        {label: 'All risks', value: 'all'},
        {label: 'Healthy', value: 'healthy'},
        {label: 'Watching', value: 'watch'},
        {label: 'At risk', value: 'risk'},
        {label: 'Critical', value: 'critical'},
      ],
    },
    card: {
      statuses: {active: 'Active', paused: 'Paused', closed: 'Closed', draft: 'Draft'},
      aiWatching: 'AI monitoring',
      edit: 'Edit',
      publish: 'Publish',
      pause: 'Pause',
      more: 'More actions',
      applications: 'Applications',
      qualified: 'qualified',
      match: 'Match',
      average: 'Avg.',
      strongSignal: 'Strong signal for shortlist',
      views: 'Views',
      conversion: 'Conversion',
      salary: 'Salary',
      salaryVisible: 'Transparent',
      salaryHidden: 'Hidden',
      salaryRangeMissing: 'No salary range',
      salaryVisiblePrefix: 'Visible',
      salaryHiddenPrefix: 'Hidden',
      riskSignals: 'AI risk signals',
    },
    quality: {
      badge: 'Job Quality',
      description: 'Publishing quality, talent pool impact and conversion risk.',
      scoreLabel: 'Quality',
      risk: 'Risk',
      watch: 'Watch',
      conversion: 'Conversion',
      optimize: 'Optimize job',
      preview: 'Preview',
    },
    metricTrends: {week: 'this week', quality: 'quality', improved: 'improved', risk: 'risk'},
    pagination: {
      previous: 'Previous',
      next: 'Next',
      pageSize: 'Per page',
      summary: (start: number, end: number, total: number) =>
        total === 0 ? 'No records' : `${start}-${end} of ${total} jobs`,
    },
  };

  return lang === 'tr' ? tr : en;
}

export function getEmployerTalentCopy(locale: string) {
  const lang = getJobsTalentLanguage(locale);
  const tr = {
    labels: {
      match: 'Uyum',
      intent: 'Niyet',
      candidate: 'aday',
      candidates: 'aday',
      skills: 'beceri',
      tags: 'etiket',
      notes: 'not',
      years: 'yıl',
      today: 'Bugün',
      yesterday: 'Dün',
      salaryNotSpecified: 'Belirtilmedi',
      synced: 'Senkronize',
      offline: 'Çevrim dışı yedek',
      syncing: 'Senkronize ediliyor',
    },
    hero: {
      badge: 'Yapay zekâ aday kaynak merkezi',
      decisionFlow: 'İnsan onaylı karar akışı',
      title: 'Yetenek Radarı: en iyi adayı kaçırmadan bulun, anlayın ve aksiyona geçin.',
      description: 'Doğal dil araması, açıklanabilir uyum puanı, aday süreci ve davet kampanyaları tek üretim ekranında birleşir.',
      searchLabel: 'Yetenek Radarı araması',
      searchPlaceholder: 'Örn. React + TypeScript, İstanbul hibrit, 85+ uyum, hemen başlayabilir...',
      suggestionsTitle: 'Hazır aramalar',
      openMatchCenter: 'Uyum merkezini aç',
      resultSummary: (result: number, total: number) => `${result}/${total} aday gösteriliyor`,
      smartQueries: [
        'Kıdemli ön yüz geliştirici, React + TypeScript, İstanbul hibrit, maaş bandına uyumlu',
        'Son 7 günde aktif, hemen başlayabilecek, uyum puanı 85+',
        'Tasarım sistemi deneyimi olan ürün tasarımcısı, uzaktan çalışabilir',
        'Go/gRPC arka uç, yüksek niyet puanı, referans veya radar kaynağı',
      ],
    },
    insight: {
      avgMatch: 'Ortalama uyum',
      poolQuality: 'Aday havuzu kalitesi',
      highScore: '85+ aday',
      waitingAction: 'Bugün aksiyon bekliyor',
      fastAvailable: 'Hızlı müsait',
      withinTwoWeeks: '≤ 2 hafta içinde',
      radarSourced: 'Radar kaynaklı',
      passiveSourcing: 'Pasif aday fırsatı',
    },
    center: {
      badgeRadar: 'Yetenek Radarı',
      badgeExplainable: 'Açıklanabilir eşleşme',
      title: 'Aday operasyon merkezi',
      description: 'Arama, filtreleme, kısa liste, süreç ve aday zekâsı tek akışta. İşe alım ekibinin günlük masası burada başlar.',
      importCv: 'CV içe aktar',
      campaign: 'Davet kampanyası',
      aiShortlist: 'Yapay zekâ kısa listesi',
      filters: 'Filtreler',
      sortLabel: 'Aday sıralama',
      export: 'Dışa aktar',
      clearAll: 'Tümünü temizle',
      noResultsTitle: 'Bu filtrelerle aday bulunamadı',
      noResultsDesc: 'Skor eşiğini düşürün, rol filtresini kaldırın ya da arama kutusunda daha geniş bir niyet yazın.',
      resetFilters: 'Filtreleri sıfırla',
      sort: {
        recommended: 'Radar önerisi',
        match: 'En yüksek uyum',
        intent: 'En yüksek niyet',
        recent: 'Son aktiflik',
        salary: 'Maaş uyumu',
      },
      views: {radar: 'Radar', pipeline: 'Süreç', compare: 'Karşılaştır', outreach: 'Davet'},
    },
    filters: {
      title: 'Akıllı filtreler',
      activeSignals: (count: number) => `${count} aktif sinyal`,
      clear: 'Filtreleri temizle',
      roleFocus: 'Rol odağı',
      allRoles: 'Tüm roller',
      status: 'Süreç durumu',
      allStatuses: 'Tüm durumlar',
      source: 'Kaynak',
      allSources: 'Tüm kaynaklar',
      availability: 'Müsaitlik',
      allAvailabilities: 'Tüm müsaitlikler',
      minMatch: 'Minimum uyum',
      qualityThreshold: 'Aday kalitesi eşiği',
      broad: 'Geniş',
      selective: 'Seçici',
      active: {
        search: 'Arama',
        role: 'Rol',
        status: 'Durum',
        source: 'Kaynak',
        availability: 'Müsaitlik',
        score: 'Skor',
      },
      presets: [
        {id: 'hot', label: 'Sıcak adaylar', description: '85+ uyum ve yüksek niyet'},
        {id: 'fast', label: 'Hızlı kapanış', description: 'Hemen/2 hafta içinde müsait'},
        {id: 'salary', label: 'Maaş uyumlu', description: 'Band üstüne taşmayan adaylar'},
        {id: 'radar', label: 'Radar kaynaklı', description: 'Aktif aday kaynağı fırsatları'},
      ],
    },
    card: {
      availability: 'Müsaitlik',
      source: 'Kaynak',
      salary: 'Maaş',
      moreSkills: (count: number) => `+${count} beceri`,
      moreTags: (count: number) => `+${count} etiket`,
      noteCount: (count: number) => `${count} not`,
      aiSuggestion: 'Yapay zekâ önerisi',
      risk: 'Risk',
      inspect360: '360 incele',
      profile: 'Profil',
    },
    detail: {
      open360: 'Aday 360 panelini aç',
      more: 'Diğer aksiyonlar',
      selectCandidateTitle: 'Aday seçin',
      selectCandidateDesc: 'Sol listeden aday seçtiğinizde uyum gerekçesi, riskler ve aksiyon önerileri burada görünür.',
      location: 'Lokasyon',
      experience: 'Deneyim',
      availability: 'Müsaitlik',
      salary: 'Maaş',
      nextBestAction: 'Önerilen sonraki adım',
      positiveSignals: 'Güçlü sinyaller',
      risksToVerify: 'Doğrulanacak riskler',
      skillEvidence: 'Beceri kanıtı',
      matched: 'Eşleşti',
      extra: 'Ekstra',
      intermediate: 'orta',
      candidate360: 'Aday 360',
      scheduleInterview: 'Görüşme planla',
      shortlist: 'Kısa liste',
      fullProfile: 'Tam profil',
      explainableTitle: 'Açıklanabilir yapay zekâ modu',
      explainableDesc: 'Skorlar karar yerine öneri üretir. Kısa liste veya ret aksiyonları insan onayı ve gerekçe ile ilerler.',
      verifyInInterview: 'Görüşmede doğrula',
      aiAuthor: 'Hiring Radar yapay zekâsı',
      opsAuthor: 'İşe alım operasyonu',
      you: 'Sen',
    },
    pipeline: {
      initialContact: 'İlk temas',
      screening: 'Ön eleme',
      hiringManager: 'İşe alım yöneticisi',
      scheduling: 'Planlama',
      closing: 'Kapanış',
      emptyStage: 'Bu aşamada aday yok',
    },
  };

  const en = {
    labels: {
      match: 'Match',
      intent: 'Intent',
      candidate: 'candidate',
      candidates: 'candidates',
      skills: 'skills',
      tags: 'tags',
      notes: 'notes',
      years: 'years',
      today: 'Today',
      yesterday: 'Yesterday',
      salaryNotSpecified: 'Not specified',
      synced: 'Synced',
      offline: 'Offline fallback',
      syncing: 'Syncing',
    },
    hero: {
      badge: 'AI sourcing command center',
      decisionFlow: 'Human-reviewed decision flow',
      title: 'Talent Radar: find, understand and act on the right candidate before you miss them.',
      description: 'Natural-language search, explainable match scoring, pipeline workflow and invite campaigns in one production workspace.',
      searchLabel: 'Talent Radar search',
      searchPlaceholder: 'E.g. React + TypeScript, Istanbul hybrid, 85+ match, available now...',
      suggestionsTitle: 'Ready searches',
      openMatchCenter: 'Open match center',
      resultSummary: (result: number, total: number) => `Showing ${result}/${total} candidates`,
      smartQueries: [
        'Senior frontend, React + TypeScript, Istanbul hybrid, salary-band fit',
        'Active in the last 7 days, available immediately, match score 85+',
        'Product designer with design system experience, remote-friendly',
        'Go/gRPC backend, high intent score, referral or radar source',
      ],
    },
    insight: {
      avgMatch: 'Average match',
      poolQuality: 'Talent pool quality',
      highScore: '85+ candidates',
      waitingAction: 'Waiting for action today',
      fastAvailable: 'Fast availability',
      withinTwoWeeks: 'Within 2 weeks',
      radarSourced: 'Radar sourced',
      passiveSourcing: 'Passive sourcing opportunity',
    },
    center: {
      badgeRadar: 'Talent Radar',
      badgeExplainable: 'Explainable matching',
      title: 'Candidate operations center',
      description: 'Search, filters, shortlist, pipeline and candidate intelligence in one workflow. This is where the recruiting team starts its day.',
      importCv: 'Import CVs',
      campaign: 'Invite campaign',
      aiShortlist: 'AI shortlist',
      filters: 'Filters',
      sortLabel: 'Candidate sorting',
      export: 'Export',
      clearAll: 'Clear all',
      noResultsTitle: 'No candidates found with these filters',
      noResultsDesc: 'Lower the score threshold, remove the role filter or broaden your intent in the search box.',
      resetFilters: 'Reset filters',
      sort: {
        recommended: 'Radar recommendation',
        match: 'Highest match',
        intent: 'Highest intent',
        recent: 'Recent activity',
        salary: 'Salary fit',
      },
      views: {radar: 'Radar', pipeline: 'Pipeline', compare: 'Compare', outreach: 'Invite'},
    },
    filters: {
      title: 'Smart filters',
      activeSignals: (count: number) => `${count} active signals`,
      clear: 'Clear filters',
      roleFocus: 'Role focus',
      allRoles: 'All roles',
      status: 'Pipeline status',
      allStatuses: 'All statuses',
      source: 'Source',
      allSources: 'All sources',
      availability: 'Availability',
      allAvailabilities: 'All availability',
      minMatch: 'Minimum match',
      qualityThreshold: 'Candidate quality threshold',
      broad: 'Broad',
      selective: 'Selective',
      active: {
        search: 'Search',
        role: 'Role',
        status: 'Status',
        source: 'Source',
        availability: 'Availability',
        score: 'Score',
      },
      presets: [
        {id: 'hot', label: 'Hot candidates', description: '85+ match and high intent'},
        {id: 'fast', label: 'Fast close', description: 'Immediate or within 2 weeks'},
        {id: 'salary', label: 'Salary fit', description: 'Candidates within the band'},
        {id: 'radar', label: 'Radar sourced', description: 'Active sourcing opportunities'},
      ],
    },
    card: {
      availability: 'Availability',
      source: 'Source',
      salary: 'Salary',
      moreSkills: (count: number) => `+${count} skills`,
      moreTags: (count: number) => `+${count} tags`,
      noteCount: (count: number) => `${count} notes`,
      aiSuggestion: 'AI suggestion',
      risk: 'Risk',
      inspect360: 'Inspect 360',
      profile: 'Profile',
    },
    detail: {
      open360: 'Open Candidate 360 panel',
      more: 'More actions',
      selectCandidateTitle: 'Select a candidate',
      selectCandidateDesc: 'Select a candidate from the list to see match rationale, risks and recommended actions here.',
      location: 'Location',
      experience: 'Experience',
      availability: 'Availability',
      salary: 'Salary',
      nextBestAction: 'Next best action',
      positiveSignals: 'Strong signals',
      risksToVerify: 'Risks to verify',
      skillEvidence: 'Skill evidence',
      matched: 'Matched',
      extra: 'Extra',
      intermediate: 'intermediate',
      candidate360: 'Candidate 360',
      scheduleInterview: 'Schedule interview',
      shortlist: 'Shortlist',
      fullProfile: 'Full profile',
      explainableTitle: 'Explainable AI mode',
      explainableDesc: 'Scores create recommendations, not decisions. Shortlist or reject actions require human review and rationale.',
      verifyInInterview: 'Verify in interview',
      aiAuthor: 'Hiring Radar AI',
      opsAuthor: 'Recruiting Ops',
      you: 'You',
    },
    pipeline: {
      initialContact: 'Initial contact',
      screening: 'Screening',
      hiringManager: 'Hiring manager',
      scheduling: 'Scheduling',
      closing: 'Closing',
      emptyStage: 'No candidates in this stage',
    },
  };

  return lang === 'tr' ? tr : en;
}
