import {normalizeEmployerLanguage, type EmployerLanguage} from './employer-copy';
import type {EmployerCandidateOpportunity, EmployerCandidateStatus, EmployerWorkModel} from '@/types/employer';

export function getTalentWorkflowLanguage(locale: string): EmployerLanguage {
  return normalizeEmployerLanguage(locale);
}

export const workflowCandidateStatusLabels: Record<EmployerLanguage, Record<EmployerCandidateStatus, string>> = {
  tr: {
    new: 'Yeni',
    reviewed: 'İncelendi',
    shortlisted: 'Kısa liste',
    interview: 'Görüşme',
    offer: 'Teklif',
    hired: 'İşe alındı',
    rejected: 'Reddedildi',
  },
  en: {
    new: 'New',
    reviewed: 'Reviewed',
    shortlisted: 'Shortlisted',
    interview: 'Interview',
    offer: 'Offer',
    hired: 'Hired',
    rejected: 'Rejected',
  },
};

export const workflowAvailabilityLabels: Record<EmployerLanguage, Record<EmployerCandidateOpportunity['availability'], string>> = {
  tr: {immediate: 'Hemen', two_weeks: '2 hafta', one_month: '1 ay', passive: 'Pasif'},
  en: {immediate: 'Immediate', two_weeks: '2 weeks', one_month: '1 month', passive: 'Passive'},
};

export const workflowWorkModelLabels: Record<EmployerLanguage, Record<EmployerWorkModel | 'flexible', string>> = {
  tr: {office: 'Ofis', hybrid: 'Hibrit', remote: 'Uzaktan', flexible: 'Esnek'},
  en: {office: 'Office', hybrid: 'Hybrid', remote: 'Remote', flexible: 'Flexible'},
};

export const workflowSourceLabels: Record<EmployerLanguage, Record<EmployerCandidateOpportunity['source'], string>> = {
  tr: {
    direct: 'Doğrudan başvuru',
    linkedin: 'LinkedIn',
    referral: 'Referans',
    job_board: 'İlan platformu',
    talent_radar: 'Yetenek Radarı',
    agency: 'Ajans',
    other: 'Diğer',
  },
  en: {
    direct: 'Direct application',
    linkedin: 'LinkedIn',
    referral: 'Referral',
    job_board: 'Job board',
    talent_radar: 'Talent Radar',
    agency: 'Agency',
    other: 'Other',
  },
};

export function formatWorkflowSalary(candidate: EmployerCandidateOpportunity, locale: string) {
  const lang = getTalentWorkflowLanguage(locale);
  if (!candidate.salaryExpectation) return lang === 'tr' ? 'Belirtilmedi' : 'Not specified';
  const {min, max, currency} = candidate.salaryExpectation;
  const formatterLocale = lang === 'tr' ? 'tr-TR' : 'en-US';
  return `${min.toLocaleString(formatterLocale)}-${max.toLocaleString(formatterLocale)} ${currency}`;
}

export function formatWorkflowDateTime(locale: string, date = new Date()) {
  const lang = getTalentWorkflowLanguage(locale);
  return new Intl.DateTimeFormat(lang === 'tr' ? 'tr-TR' : 'en-US', {
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

export function getTalentWorkflowCopy(locale: string) {
  const lang = getTalentWorkflowLanguage(locale);
  const tr = {
    common: {
      match: 'Uyum',
      intent: 'Niyet',
      weighted: 'Ağırlıklı',
      health: 'Sağlık',
      response: 'Yanıt',
      candidate: 'aday',
      candidates: 'aday',
      notes: 'not',
      tags: 'etiket',
      status: 'Durum',
      source: 'Kaynak',
      salary: 'Maaş',
      availability: 'Müsaitlik',
      experience: 'Deneyim',
      location: 'Lokasyon',
      years: 'yıl',
      notSpecified: 'Belirtilmedi',
      active: 'aktif',
      now: 'Şimdi',
      next: 'Sıradaki',
      clear: 'Temizle',
      copy: 'Kopyala',
      copied: 'Kopyalandı',
      close: 'Kapat',
      profile360: 'Aday 360',
      fullProfile: 'Tam profil',
      humanReview: 'İnsan onayı',
      humanReviewMode: 'İnsan onay modu',
      explainableAi: 'Açıklanabilir yapay zekâ',
      aiDecisionSupport: 'Yapay zekâ karar desteği',
      backendQueue: 'Arka uç kuyruğu',
      draftSimulation: 'Taslak simülasyon',
      ready: 'Hazır',
      review: 'Kontrol',
      blocked: 'Engelli',
      blocker: 'Engel',
      warning: 'Uyarı',
      warnings: 'uyarı',
      blockers: 'engel',
      saved: 'Kaydedildi',
      draft: 'Taslak',
      campaign: 'Kampanya',
      queue: 'Kuyruk',
      audit: 'Denetim',
      compliance: 'Uyumluluk',
      quality: 'Kalite',
      readiness: 'Hazırlık',
      channel: 'Kanal',
      template: 'Şablon',
      tone: 'Ton',
      followUp: 'Takip',
      personalization: 'Kişiselleştirme',
    },
    drawer: {
      closeCandidate360: 'Aday 360 panelini kapat',
      closePanel: 'Paneli kapat',
      activeSuffix: 'aktif',
      salaryHelper: 'İlk görüşmede teyit',
      matchDescription: 'Uyum puanı; rol uyumu, beceri kanıtı, maaş/lokasyon uyumu ve son aktivite sinyallerinin açıklanabilir birleşimidir.',
    },
    nextActions: {
      eyebrow: 'Önerilen sonraki adım',
      writeMessage: 'Mesaj yaz',
      scheduleInterview: 'Görüşme planla',
      shortlist: 'Kısa listeye al',
      addToCampaign: 'Kampanyaya ekle',
      archive: 'Arşivle',
    },
    explainable: {
      badge: 'Açıklanabilir uyum',
      humanApproval: 'İnsan onayı gerekir',
      title: 'Neden bu aday?',
      description: 'Bu skor karar değil, karar desteğidir. Aşağıdaki ağırlıklı bileşenler insan görüşmesiyle doğrulanmalıdır.',
      requiredSkills: 'Zorunlu beceri uyumu',
      skillsEvidence: (matched: number, total: number, skills: string) => `${matched}/${total} kritik beceri eşleşiyor: ${skills || 'eşleşen beceri yok'}.`,
      roleExperience: 'Rol ve deneyim seviyesi',
      workModel: 'Lokasyon / çalışma modeli',
      salaryFit: 'Maaş bandı uyumu',
      salaryEvidence: (salary: string) => `Beklenti ${salary}; üst banda yakınlık kontrol edilmeli.`,
      salaryMissing: 'Maaş beklentisi belirtilmedi; ilk görüşmede mutlaka doğrulanmalı.',
      intentAccess: 'Niyet ve erişilebilirlik',
      verificationRisk: 'Doğrulama riski',
      verificationEvidence: (count: number) => count > 0 ? `${count} risk görüşmede doğrulanmalı.` : 'Belirgin risk sinyali yok; standart referans kontrolü yeterli olabilir.',
    },
    risk: {
      needsVerification: 'Doğrulama gerekli',
      lowRisk: 'Düşük risk',
      title: 'Risk ve görüşme doğrulaması',
      description: 'Karar kalitesini artırmak için riskleri görüşme ve referans adımlarında doğrulayın.',
      riskSignals: 'Risk sinyalleri',
      noClearRisk: 'Belirgin risk yok',
      noClearRiskLong: 'Mevcut veriyle belirgin risk yok; yine de rol beklentisi, maaş ve çalışma modeli teyit edilmeli.',
      questions: 'Sorulacak net sorular',
    },
    timeline: {
      eyebrow: 'Zaman çizelgesi',
      title: 'Aday aktivite akışı',
      sourceTitle: 'Aday kaynağı oluştu',
      sourceRadar: 'Yetenek Radarı tarafından önerildi.',
      sourcePool: 'Aday havuzuna eklendi.',
      activityTitle: 'Son aktivite sinyali',
      reviewTitle: 'Yapay zekâ ön değerlendirme',
      nextTitle: 'Önerilen insan aksiyonu',
    },
    skillEvidence: {
      title: 'Beceri kanıtı',
      description: 'Adayın becerilerini karar için kanıta bağlayın; eksikleri görüşmede doğrulayın.',
      matched: 'Eşleşti',
      extra: 'Ekstra',
      years: 'yıl',
      noEvidence: 'Kanıt metni yok',
    },
    workflow: {
      badge: 'İşe alım çalışma alanı',
      title: 'Notlar, etiketler ve ekip hafızası',
      description: (name: string) => `${name} için karar geçmişini, takip sinyallerini ve hızlı aksiyonları tek yerde tut.`,
      tags: 'Etiketler',
      active: 'aktif',
      removeTag: 'Etiketi kaldır',
      noTags: 'Henüz etiket yok',
      tagPlaceholder: 'Etiket ekle: işe alım yöneticisi bekliyor, sıcak aday...',
      add: 'Ekle',
      quickNote: 'Hızlı not',
      notePlaceholder: 'Görüşme notu, takip kararı, işe alım yöneticisi yorumu...',
      notePersistence: 'Notlar arka uç ile senkronize edilir; bağlantı yoksa yerel yedek kullanılır.',
      saveNote: 'Notu kaydet',
      activity: 'Aktivite akışı',
      lastUpdate: 'Son güncelleme',
      noNotes: 'Bu aday için henüz ekip notu yok. İlk notu ekleyip karar bağlamını kaybetme.',
      moveToShortlist: 'Kısa listeye taşı',
      setFollowUp: 'Takip kur',
      askHm: 'Yönetici yorumu iste',
      archive: 'Arşivle',
      quickTags: ['Sıcak aday', 'Yönetici bekliyor', 'Maaş uyumlu', 'Teknik güçlü', 'Takip', 'Risk kontrolü'],
    },
    pipeline: {
      title: 'Süreç panosu',
      subtitle: 'Adayları aşamalar arasında yönetin, gecikmeleri görün ve toplu aksiyon alın.',
      selected: 'seçili',
      bulkMove: 'Toplu taşı',
      bulkTag: 'Toplu etiket',
      bulkNote: 'Toplu not',
      move: 'Taşı',
      tagPlaceholder: 'Etiket',
      notePlaceholder: 'Seçili adaylara not düş...',
      addTag: 'Etiketle',
      addNote: 'Not düş',
      archiveSelected: 'Seçilileri arşivle',
      activeCandidates: 'Aktif aday',
      hotOpportunities: 'Sıcak fırsat',
      waitingFeedback: 'Geri bildirim bekleyen',
      overdue: 'Hedef süre dışı',
      avgMatch: 'Ortalama uyum',
      stageEmpty: 'Bu aşamada aday yok',
      dragHere: 'Adayı buraya sürükleyin',
      daysInStage: (days: number) => `${days} gündür aşamada`,
      slaLate: (days: number) => `Hedef +${days}g`,
      nextStage: 'Sonraki aşamaya taşı',
      inspect: '360 incele',
    },
    compare: {
      emptyTitle: 'Karşılaştırma için aday yok',
      emptyDescription: 'Filtreleri genişletin veya Radar görünümünden aday seçin.',
      strongestDecision: 'En güçlü karar',
      fastestClose: 'En hızlı kapanış',
      lowestRisk: 'En düşük risk',
      bestBudgetFit: 'En iyi bütçe uyumu',
      decisionIntelligence: 'Karar zekâsı',
      criticalSkills: (count: number) => `${count} kritik beceri`,
      title: 'Aday karşılaştırma matrisi',
      description: 'Adayları uyum, beceri kapsamı, maaş, müsaitlik, risk ve insan kontrolü odağıyla yan yana değerlendirin.',
      aiRecommendation: (best: string, fastest: string) => `Yapay zekâ önerisi: ${best} ile görüşmeyi öncele; ${fastest} için hızlı takip hazırla.`,
      decisionSummary: 'Karar özeti',
      calibration: 'Kısa liste kalibrasyonu',
      skillCoverage: 'Beceri kapsamı',
      intentWarmth: 'Niyet / sıcaklık',
      salaryFit: 'Maaş uyumu',
      closeSpeed: 'Kapanış hızı',
      riskMatrix: 'Risk matrisi',
      nextAction: 'Önerilen aksiyon',
      open360: '360 aç',
      select: 'Seç',
      noEvidence: 'Kanıt yok',
    },
    outreach: {
      view: 'Davet',
      composerBadge: 'Davet hazırlayıcı',
      title: 'Adaya özel davet kampanyası oluşturun.',
      description: 'Aday seçin, kanal ve tonu belirleyin; mesaj kalitesini kontrol edip kampanya taslağını güvenli şekilde kaydedin.',
      readiness: 'Kampanya hazırlığı',
      responseEstimate: 'Yanıt tahmini',
      selectCandidate: 'Aday seçimi',
      chooseChannel: 'Kanal seçimi',
      messageTone: 'Mesaj tonu',
      template: 'Şablon',
      personalizationDepth: 'Kişiselleştirme derinliği',
      followUpCadence: 'Takip ritmi',
      guardrails: 'Koruma kuralları',
      subject: 'Konu',
      message: 'Mesaj',
      preview: 'Önizleme',
      qualityCheck: 'Kalite kontrolü',
      draftHistory: 'Taslak geçmişi',
      saveDraft: 'Kampanya taslağı oluştur',
      saving: 'Kaydediliyor...',
      fixBlocker: 'Önce engeli düzelt',
      selectToPreview: 'Mesaj önizlemek için bir aday seçin.',
      useAiText: 'Yapay zekâ metnine dön',
      copyMessage: 'Mesajı kopyala',
      open360: '360 profil aç',
      complianceNote: 'Mesaj yalnızca beceri, rol uyumu, müsaitlik ve açık iş bilgileri üzerinden üretilir; hassas özellik veya varsayım kullanmaz.',
      blockersTitle: 'Engeller',
      warningsTitle: 'İyileştirme önerileri',
      strengthsTitle: 'Güçlü yanlar',
      noDrafts: 'Henüz kampanya taslağı yok',
      candidateMessages: 'Aday mesajları',
      channels: {
        email: {label: 'E-posta', helper: 'Kurumsal, ölçülebilir ve takip edilebilir', risk: 'Konu satırı net olmalı'},
        linkedin: {label: 'LinkedIn', helper: 'Pasif adaylara sıcak ve profesyonel temas', risk: 'Mesaj kısa tutulmalı'},
        whatsapp: {label: 'WhatsApp', helper: 'Sıcak adaylarda hızlı kapanış', risk: 'İzin ve bağlam hassas'},
      },
      tones: {
        warm: {label: 'Sıcak', helper: 'Samimi ama profesyonel'},
        direct: {label: 'Net', helper: 'Kısa, aksiyon odaklı'},
        premium: {label: 'Üst düzey', helper: 'Deneyimli aday dili'},
        technical: {label: 'Teknik', helper: 'Beceri kanıtını öne çıkarır'},
      },
      templates: {
        'role-fit': {label: 'Rol uyumu', helper: 'Uyum gerekçesini anlatır', badge: 'Genel'},
        'quick-intro': {label: 'Hızlı tanışma', helper: 'Cevap bariyerini düşürür', badge: 'Kısa'},
        'technical-depth': {label: 'Teknik derinlik', helper: 'Kıdemli adaylar için', badge: 'Kıdemli'},
        'salary-transparent': {label: 'Şeffaf teklif', helper: 'Maaş ve çalışma modelini açar', badge: 'Şeffaf'},
      },
      followUps: {
        none: {label: 'Takip yok', helper: 'Sadece ilk temas'},
        three_day: {label: '3 gün sonra', helper: 'Sıcak adaylar için ideal'},
        five_day: {label: '5 gün sonra', helper: 'Daha sakin takip'},
      },
      personalization: {
        concise: {label: 'Kısa', helper: 'LinkedIn/WhatsApp için uygun'},
        balanced: {label: 'Dengeli', helper: 'En iyi varsayılan'},
        deep: {label: 'Derin', helper: 'Kıdemli adaylarda kanıtlı anlatım'},
      },
    },
    campaignDetail: {
      close: 'Kampanya panelini kapat',
      tabs: {queue: 'Kuyruk', review: 'Kontrol panosu', analytics: 'Analitik', messages: 'Mesajlar', guardrails: 'Kalite / Kurallar'},
      prepareQueue: 'Gönderim kuyruğunu hazırla',
      preparing: 'Hazırlanıyor...',
      queuePrepared: 'Kuyruk hazırlandı',
      readyToSend: 'Gönderime hazır',
      needsReview: 'Kontrol gerekiyor',
      hasBlocker: 'Engelli',
      sendQueue: 'Gönderim kuyruğu',
      messageVariants: 'Mesaj varyantları',
      qaGuardrails: 'Kalite ve koruma kuralları',
      campaignReadiness: 'Kampanya hazırlığı',
      responseEstimate: 'Yanıt tahmini',
      auditTrail: 'Denetim izi',
      open360: '360 aç',
      copyMessage: 'Mesajı kopyala',
      queueFirst: 'Durum güncellemek için önce kuyruğu hazırlayın.',
    },
    reviewBoard: {
      title: 'Gönderim kontrol panosu',
      description: 'İnsan kontrolüyle aday bazlı gönderim kararlarını yönetin.',
      ready: 'Gönderime hazır',
      review: 'Kontrol gerekiyor',
      blocked: 'Engelli',
      markReady: 'Hazır yap',
      markReview: 'Kontrole al',
      markBlocked: 'Engelle',
      inspector: 'Aday denetçisi',
      selectItem: 'Bir kuyruk öğesi seçin',
      backendSaved: 'Arka uçta kayıtlı',
      localDraft: 'Yerel taslak',
      checks: 'Kontroller',
      noItems: 'Bu durumda aday yok',
    },
    campaignAnalytics: {
      badge: 'Kampanya analitiği',
      title: 'Kampanya sağlık merkezi',
      description: 'Kampanyanın gönderime hazır olup olmadığını, insan kontrol yükünü ve yanıt potansiyelini tek panelde görün.',
      campaignHealth: 'Kampanya sağlığı',
      readyRate: 'Gönderime hazır',
      reviewLoad: 'Kontrol yükü',
      compliance: 'Uyumluluk',
      funnelReadiness: 'Hazırlık hunisi',
      statusDistribution: 'Gönderim öncesi aday durum dağılımı',
      candidatePotential: 'Aday potansiyeli',
      potentialDesc: 'Yanıt ihtimali, uyum ve niyet sinyalleri',
      avgMatch: 'Ortalama uyum',
      avgIntent: 'Ortalama niyet',
      fastClose: 'Hızlı kapanış',
      reviewReasons: 'Kontrol nedenleri',
      channelIntelligence: 'Kanal zekâsı',
      auditTrend: 'Denetim eğilimi',
      sourceMix: 'Kaynak dağılımı',
    },
  };

  const en = {
    common: {
      match: 'Match', intent: 'Intent', weighted: 'Weighted', health: 'Health', response: 'Response', candidate: 'candidate', candidates: 'candidates', notes: 'notes', tags: 'tags', status: 'Status', source: 'Source', salary: 'Salary', availability: 'Availability', experience: 'Experience', location: 'Location', years: 'years', notSpecified: 'Not specified', active: 'active', now: 'Now', next: 'Next', clear: 'Clear', copy: 'Copy', copied: 'Copied', close: 'Close', profile360: 'Candidate 360', fullProfile: 'Full profile', humanReview: 'Human review', humanReviewMode: 'Human review mode', explainableAi: 'Explainable AI', aiDecisionSupport: 'AI decision support', backendQueue: 'Backend queue', draftSimulation: 'Draft simulation', ready: 'Ready', review: 'Review', blocked: 'Blocked', blocker: 'Blocker', warning: 'Warning', warnings: 'warnings', blockers: 'blockers', saved: 'Saved', draft: 'Draft', campaign: 'Campaign', queue: 'Queue', audit: 'Audit', compliance: 'Compliance', quality: 'Quality', readiness: 'Readiness', channel: 'Channel', template: 'Template', tone: 'Tone', followUp: 'Follow-up', personalization: 'Personalization'},
    drawer: {closeCandidate360: 'Close Candidate 360 panel', closePanel: 'Close panel', activeSuffix: 'active', salaryHelper: 'Verify in first call', matchDescription: 'Match score is an explainable blend of role fit, skill evidence, salary/location fit and recent activity signals.'},
    nextActions: {eyebrow: 'Next best action', writeMessage: 'Write message', scheduleInterview: 'Schedule interview', shortlist: 'Shortlist', addToCampaign: 'Add to campaign', archive: 'Archive'},
    explainable: {badge: 'Explainable match', humanApproval: 'Human approval required', title: 'Why this candidate?', description: 'This score is decision support, not a decision. The weighted factors below should be verified by humans.', requiredSkills: 'Required skill fit', skillsEvidence: (matched: number, total: number, skills: string) => `${matched}/${total} critical skills match: ${skills || 'no matched skills'}.`, roleExperience: 'Role and experience level', workModel: 'Location / work model', salaryFit: 'Salary-band fit', salaryEvidence: (salary: string) => `Expectation ${salary}; check proximity to upper band.`, salaryMissing: 'Salary expectation is missing; verify in the first conversation.', intentAccess: 'Intent and accessibility', verificationRisk: 'Verification risk', verificationEvidence: (count: number) => count > 0 ? `${count} risks should be verified in interview.` : 'No clear risk signals; standard reference checks may be enough.'},
    risk: {needsVerification: 'Verification required', lowRisk: 'Low risk', title: 'Risk and interview verification', description: 'Verify risks in interview and reference steps to improve decision quality.', riskSignals: 'Risk signals', noClearRisk: 'No clear risk', noClearRiskLong: 'No clear risk in current data; still verify role expectations, compensation and work model.', questions: 'Clear questions to ask'},
    timeline: {eyebrow: 'Timeline', title: 'Candidate activity stream', sourceTitle: 'Candidate source created', sourceRadar: 'Recommended by Talent Radar.', sourcePool: 'Added to the talent pool.', activityTitle: 'Recent activity signal', reviewTitle: 'AI pre-screening', nextTitle: 'Recommended human action'},
    skillEvidence: {title: 'Skill evidence', description: 'Tie candidate skills to evidence for decisions; verify missing areas in interviews.', matched: 'Matched', extra: 'Extra', years: 'years', noEvidence: 'No evidence text'},
    workflow: {badge: 'Recruiter workspace', title: 'Notes, tags and team memory', description: (name: string) => `Keep decision history, follow-up signals and quick actions for ${name} in one place.`, tags: 'Tags', active: 'active', removeTag: 'Remove tag', noTags: 'No tags yet', tagPlaceholder: 'Add tag: hiring manager waiting, hot candidate...', add: 'Add', quickNote: 'Quick note', notePlaceholder: 'Interview note, follow-up decision, hiring manager comment...', notePersistence: 'Notes sync with the backend; offline fallback is used when the connection is unavailable.', saveNote: 'Save note', activity: 'Activity stream', lastUpdate: 'Last update', noNotes: 'No team note for this candidate yet. Add the first note to preserve decision context.', moveToShortlist: 'Move to shortlist', setFollowUp: 'Set follow-up', askHm: 'Ask hiring manager', archive: 'Archive', quickTags: ['Hot candidate', 'Manager waiting', 'Salary fit', 'Technically strong', 'Follow-up', 'Risk check']},
    pipeline: {title: 'Pipeline board', subtitle: 'Move candidates through stages, surface delays and run bulk actions.', selected: 'selected', bulkMove: 'Bulk move', bulkTag: 'Bulk tag', bulkNote: 'Bulk note', move: 'Move', tagPlaceholder: 'Tag', notePlaceholder: 'Add a note to selected candidates...', addTag: 'Add tag', addNote: 'Add note', archiveSelected: 'Archive selected', activeCandidates: 'Active candidates', hotOpportunities: 'Hot opportunities', waitingFeedback: 'Waiting feedback', overdue: 'Outside target time', avgMatch: 'Average match', stageEmpty: 'No candidates in this stage', dragHere: 'Drag a candidate here', daysInStage: (days: number) => `${days} days in stage`, slaLate: (days: number) => `Target +${days}d`, nextStage: 'Move to next stage', inspect: 'Inspect 360'},
    compare: {emptyTitle: 'No candidates to compare', emptyDescription: 'Broaden filters or select candidates from the Radar view.', strongestDecision: 'Strongest decision', fastestClose: 'Fastest close', lowestRisk: 'Lowest risk', bestBudgetFit: 'Best budget fit', decisionIntelligence: 'Decision intelligence', criticalSkills: (count: number) => `${count} critical skills`, title: 'Candidate comparison matrix', description: 'Compare candidates side by side by fit, skill coverage, compensation, availability, risk and human-review focus.', aiRecommendation: (best: string, fastest: string) => `AI recommendation: prioritize an interview with ${best}; prepare a fast follow-up for ${fastest}.`, decisionSummary: 'Decision summary', calibration: 'Shortlist calibration', skillCoverage: 'Skill coverage', intentWarmth: 'Intent / warmth', salaryFit: 'Salary fit', closeSpeed: 'Close speed', riskMatrix: 'Risk matrix', nextAction: 'Recommended action', open360: 'Open 360', select: 'Select', noEvidence: 'No evidence'},
    outreach: {
      view: 'Invite', composerBadge: 'Invite composer', title: 'Create personalized invite campaigns.', description: 'Choose candidates, channel and tone; check message quality and safely save the campaign draft.', readiness: 'Campaign readiness', responseEstimate: 'Response estimate', selectCandidate: 'Candidate selection', chooseChannel: 'Channel selection', messageTone: 'Message tone', template: 'Template', personalizationDepth: 'Personalization depth', followUpCadence: 'Follow-up cadence', guardrails: 'Guardrails', subject: 'Subject', message: 'Message', preview: 'Preview', qualityCheck: 'Quality check', draftHistory: 'Draft history', saveDraft: 'Create campaign draft', saving: 'Saving...', fixBlocker: 'Fix blocker first', selectToPreview: 'Select a candidate to preview the message.', useAiText: 'Return to AI text', copyMessage: 'Copy message', open360: 'Open 360 profile', complianceNote: 'Messages are generated only from skills, role fit, availability and explicit job context; no sensitive attributes or assumptions are used.', blockersTitle: 'Blockers', warningsTitle: 'Improvement suggestions', strengthsTitle: 'Strengths', noDrafts: 'No campaign drafts yet', candidateMessages: 'Candidate messages',
      channels: {email: {label: 'Email', helper: 'Corporate, measurable and follow-up friendly', risk: 'Subject line must be clear'}, linkedin: {label: 'LinkedIn', helper: 'Warm professional outreach to passive candidates', risk: 'Keep the message concise'}, whatsapp: {label: 'WhatsApp', helper: 'Fast close for warm candidates', risk: 'Consent and context are sensitive'}},
      tones: {warm: {label: 'Warm', helper: 'Friendly but professional'}, direct: {label: 'Direct', helper: 'Short and action-oriented'}, premium: {label: 'Premium', helper: 'Executive candidate language'}, technical: {label: 'Technical', helper: 'Highlights skill evidence'}},
      templates: {'role-fit': {label: 'Role fit', helper: 'Explains the match rationale', badge: 'General'}, 'quick-intro': {label: 'Quick intro', helper: 'Lowers the response barrier', badge: 'Short'}, 'technical-depth': {label: 'Technical depth', helper: 'For senior candidates', badge: 'Senior'}, 'salary-transparent': {label: 'Transparent offer', helper: 'Opens compensation and work model', badge: 'Transparent'}},
      followUps: {none: {label: 'No follow-up', helper: 'Only first touch'}, three_day: {label: 'After 3 days', helper: 'Ideal for warm candidates'}, five_day: {label: 'After 5 days', helper: 'A calmer follow-up'}},
      personalization: {concise: {label: 'Concise', helper: 'Good for LinkedIn/WhatsApp'}, balanced: {label: 'Balanced', helper: 'Best default'}, deep: {label: 'Deep', helper: 'Evidence-heavy for senior candidates'}},
    },
    campaignDetail: {close: 'Close campaign panel', tabs: {queue: 'Queue', review: 'Review Board', analytics: 'Analytics', messages: 'Messages', guardrails: 'QA / Guardrails'}, prepareQueue: 'Prepare send queue', preparing: 'Preparing...', queuePrepared: 'Queue prepared', readyToSend: 'Ready to send', needsReview: 'Needs review', hasBlocker: 'Blocked', sendQueue: 'Send queue', messageVariants: 'Message variants', qaGuardrails: 'QA and guardrails', campaignReadiness: 'Campaign readiness', responseEstimate: 'Response estimate', auditTrail: 'Audit trail', open360: 'Open 360', copyMessage: 'Copy message', queueFirst: 'Prepare the queue before updating item status.'},
    reviewBoard: {title: 'Send queue review board', description: 'Manage candidate-level send decisions with human review.', ready: 'Ready to send', review: 'Needs review', blocked: 'Blocked', markReady: 'Mark ready', markReview: 'Move to review', markBlocked: 'Block', inspector: 'Candidate inspector', selectItem: 'Select a queue item', backendSaved: 'Saved in backend', localDraft: 'Local draft', checks: 'Checks', noItems: 'No candidates in this status'},
    campaignAnalytics: {badge: 'Campaign Analytics', title: 'Campaign health center', description: 'See whether the campaign is ready to send, the human-review workload and response potential in one panel.', campaignHealth: 'Campaign health', readyRate: 'Ready to send', reviewLoad: 'Review load', compliance: 'Compliance', funnelReadiness: 'Funnel readiness', statusDistribution: 'Candidate status distribution before send', candidatePotential: 'Candidate potential', potentialDesc: 'Response likelihood, match and intent signals', avgMatch: 'Average match', avgIntent: 'Average intent', fastClose: 'Fast close', reviewReasons: 'Review reasons', channelIntelligence: 'Channel intelligence', auditTrend: 'Audit trend', sourceMix: 'Source mix'},
  };

  return lang === 'tr' ? tr : en;
}
